version: '3.3'

volumes:
  static_value:
  media_value:
  db_data:

services:
  db:
    image: postgres:13.0-alpine
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    networks:
      - mynetwork      
    container_name: db

  backend:
    image: kotbarbarossa/test-task-bewise:latest
    ports:
      - "8000:8000"    
    restart: always
    volumes:
      - static_value:/backend/static/
      - media_value:/backend/media/
    depends_on:
      - db
    env_file:
      - ./.env
    networks:
      - mynetwork      
    container_name: backend

  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - "80:80"
    restart: always      
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    depends_on:
      - backend
    networks:
      - mynetwork       
    container_name: nginx    

networks:
  mynetwork: