# Generated by Django 3.2.20 on 2023-10-17 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True, verbose_name='question id')),
                ('question', models.CharField(max_length=500, verbose_name='question text')),
                ('answer', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField()),
            ],
        ),
    ]
